### ISSUE TITLE
Error while installing tyton

### ISSUE THREAD

**Issue by Szewcson** [BlackArch/blackarch#3527]
### Bug description

During installation of tyton kernel module error appears

### Steps to reproduce
1.) Install tyton

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
```
(3/4) Install DKMS modules
==> dkms install --no-depmod tyton/80.56494f3 -k 5.19.10-arch1-1
Error! Bad return status for module build on kernel: 5.19.10-arch1-1 (x86_64)
Consult /var/lib/dkms/tyton/80.56494f3/build/make.log for more information.
==> WARNING: `dkms install --no-depmod tyton/80.56494f3 -k 5.19.10-arch1-1' exited 10
==> dkms install --no-depmod tyton/80.56494f3 -k 5.15.64-1.fc32.qubes.x86_64
Error! Bad return status for module build on kernel: 5.15.64-1.fc32.qubes.x86_64 (x86_64)
Consult /var/lib/dkms/tyton/80.56494f3/build/make.log for more information.
```
```
DKMS make.log for tyton-80.56494f3 for kernel 5.15.64-1.fc32.qubes.x86_64 (x86_64)
Thu Sep 22 02:19:02 PM CEST 2022
make -C /lib/modules/5.15.64-1.fc32.qubes.x86_64/build M=/var/lib/dkms/tyton/80.56494f3/build modules
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/lib/modules/5.15.64-1.fc32.qubes.x86_64/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)
  You are using:           gcc (GCC) 12.2.0
  CC [M]  /var/lib/dkms/tyton/80.56494f3/build/src/core.o
  CC [M]  /var/lib/dkms/tyton/80.56494f3/build/src/util.o
  CC [M]  /var/lib/dkms/tyton/80.56494f3/build/src/proc.o
/var/lib/dkms/tyton/80.56494f3/build/src/proc.c: In function ‘analyze_fops’:
/var/lib/dkms/tyton/80.56494f3/build/src/proc.c:116:29: error: ‘module_mutex’ undeclared (first use in this function); did you mean ‘module_put’?
  116 |                 mutex_lock(&module_mutex);
      |                             ^~~~~~~~~~~~
      |                             module_put
/var/lib/dkms/tyton/80.56494f3/build/src/proc.c:116:29: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/tyton/80.56494f3/build/src/proc.o] Error 1
make[1]: *** [Makefile:1896: /var/lib/dkms/tyton/80.56494f3/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.15.64-1.fc32.qubes.x86_64/build'
make: *** [Makefile:19: module] Error 2
```

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Module should install without errors at least for arch kernel.

**Comment by noraj** [comment]
@Szewcson can you fill all sections of the issue template or else remove the unused / N/A sections but please to let empty / default sections.
